# Server
#destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", 'config.ru', 'Gemfile', 'Gemfile.lock', 'bundle']
#port:             9001
url:              http://exacttarget.github.io/fuelux
# local dev
#url:              http://localhost:4000/

# Custom vars
current_version:  3.0.2
repo:             https://github.com/ExactTarget/fuelux


download:
  source:         https://github.com/ExactTarget/fuelux/archive/3.0.2.zip
  dist:           https://github.com/ExactTarget/fuelux/raw/master/dist/fuelux.zip

blog:             http://code.exacttarget.com

cdn:
  css:            //www.fuelcdn.com/fuelux/3.0.2/css/fuelux.min.css
  js:             //www.fuelcdn.com/fuelux/3.0.2/js/fuelux.min.js
  zip:            //www.fuelcdn.com/fuelux/3.0.2/fuelux.zip

mctheme:
  css:            //www.fuelcdn.com/fuelux-mctheme/1.0.0/css/fuelux-mctheme.min.css

bootstrap:
  css:            //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
  js:             //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
  js_amd:         //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min

 # To view gh-pages locally
# bundle exec jekyll serve
